### ISSUE TITLE
Octal format for mode parameter

### ISSUE THREAD

**Issue by milisarge** [philanc/l5#2]
I noticed, mkdir and chmod function use octal format mode instead of normal format. For example it needs to use as l5.chmod(path, 438) not l5.chmod(path,666)  Is it this way?

**Comment by philanc** [comment]
Yes. The chmod or mkdir argument is an integer (C type: `int`,  4 bytes on most recent platforms).  The UNIX convention is to represent these number in base 8 (octal), which is convenient because UNIX permissions are sets of 3 bits.

C provides a lexical convention to support octal number constants:  in C, 0666 (with a '0' prefix) is an integer which decimal value is 438 as you noted.

Lua doesn't provide any way to directly enter octal constants. Only decimal and hexadecimal constants (438, 0x1b6).

To make it easy to handle integers with an octal representation, two tiny Lua functions can be defined:
```
function o2i(x)
  -- "octal-to-int": turn the string representation of an octal constant into an integer
  -- example:  o2i("666")  =>  438
  return tonumber(x, 8)
end

function i2o(n)
  -- "int-to-octal":  return the octal representation of an integer as a string
  -- example:  i2o(438)  => "0666"
  return string.format("%04o", n)
end

```

**Comment by milisarge** [comment]
thnks for detailed answer, i defined similar function as:
```
function chmod (path,mode) 
	l5.chmod(path,tonumber(tostring(mode),8)) 
end

--example
chmod("/path/a", 666)
```
